### ISSUE TITLE
[Interzone] segfault in timer.Stop

### ISSUE THREAD

**Issue by mido3ds** [mido3ds/C4IAN#18]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x5c70a4]

goroutine 10 [running]:
time.(*Timer).Stop(...)
        /usr/local/go/src/time/sleep.go:76
github.com/mido3ds/C4IAN/src/router/tables.(*Topology).Update(0xc000058000, 0x800000000a000001, 0xc000010090, 0x0, 0x0)
        /home/mahmoud/study/gp/project/src/router/tables/Topology.go:116 +0x604
github.com/mido3ds/C4IAN/src/router/zhls.(*LSRController).sendIntrazoneLSR(0xc000058140, 0xc0000adf00)
        /home/mahmoud/study/gp/project/src/router/zhls/LSR.go:85 +0x8c
github.com/mido3ds/C4IAN/src/router/zhls.(*UnicastController).listenForNeighborhoodChanges(0xc000058180)
        /home/mahmoud/study/gp/project/src/router/zhls/UnicastController.go:42 +0x59
created by github.com/mido3ds/C4IAN/src/router/zhls.(*UnicastController).Start
        /home/mahmoud/study/gp/project/src/router/zhls/UnicastController.go:36 +0x67
```

**Comment by mido3ds** [comment]
commit 4bb25c7
